#!/bin/bash
version=`python3 -c "import electrum_sibcoin; print(electrum_sibcoin.version.ELECTRUM_VERSION)"`
sig=`./electrum-sibcoin -w $SIGNING_WALLET signmessage $SIGNING_ADDRESS $version`
echo "{ \"version\":\"$version\", \"signatures\":{ \"$SIGNING_ADDRESS\":\"$sig\"}}"
