#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION electrum_sibcoin/version.py`)
SIBCOIN_ELECTRUM_VERSION=${VERSION_STRING[2]}
SIBCOIN_ELECTRUM_VERSION=${SIBCOIN_ELECTRUM_VERSION#\'}
SIBCOIN_ELECTRUM_VERSION=${SIBCOIN_ELECTRUM_VERSION%\'}
export SIBCOIN_ELECTRUM_VERSION

APK_VERSION_STRING=(`grep APK_VERSION electrum_sibcoin/version.py`)
SIBCOIN_ELECTRUM_APK_VERSION=${APK_VERSION_STRING[2]}
SIBCOIN_ELECTRUM_APK_VERSION=${SIBCOIN_ELECTRUM_APK_VERSION#\'}
SIBCOIN_ELECTRUM_APK_VERSION=${SIBCOIN_ELECTRUM_APK_VERSION%\'}
export SIBCOIN_ELECTRUM_APK_VERSION
